(library
 (name pera_harness_test_util)
 (wrapped false)
 (modules harness_test_util)
 (libraries eio cstruct))

(test
 (name entry_id_test)
 (modules entry_id_test)
 (libraries pera_harness pera_types alcotest containers unix))

(test
 (name session_types_test)
 (modules session_types_test)
 (libraries pera_harness pera_provider pera_types alcotest containers yojson))

