; Packaged provider and model catalog — shipped with pera.
; Provider names and base URLs from models.dev; pricing cross-checked with
; BerriAI/litellm model_prices_and_context_window.json.
; Users may extend or override entries in $XDG_CONFIG_HOME/pera/models.sexp.
((providers
  (((name anthropic)
    (protocol anthropic)
    (api_key_env (ANTHROPIC_API_KEY))
    (models
      (((name claude-sonnet-4-6)
        (context_window 200000)
        (max_tokens 16000)
        (thinking ((budget_medium 8000) (budget_high 32000)))
        (cost ((input_per_mtok "3") (output_per_mtok "15")
               (cache_read_per_mtok "0.30") (cache_write_per_mtok "3.75"))))
       ((name claude-haiku-4-5-20251001)
        (context_window 200000)
        (max_tokens 8192)
        (cost ((input_per_mtok "1") (output_per_mtok "5")
               (cache_read_per_mtok "0.10") (cache_write_per_mtok "1.25")))))))
   ((name openai)
    (protocol openai-completions)
    (api_key_env (OPENAI_API_KEY))
    (api "https://api.openai.com/v1")
    (compat
      ((max_tokens_field max_completion_tokens)
       (require_tool_result_name false)))
    (models
      (((name gpt-4o)
        (context_window 128000)
        (max_tokens 16384)
        (cost ((input_per_mtok "2.50") (output_per_mtok "10.00")
               (cache_read_per_mtok "1.25"))))
       ((name o3)
        (context_window 200000)
        (max_tokens 100000)
        (cost ((input_per_mtok "2") (output_per_mtok "8")
               (cache_read_per_mtok "0.50")))))))
   ((name moonshotai)
    (protocol openai-completions)
    (api_key_env (MOONSHOT_API_KEY))
    (api "https://api.moonshot.ai/v1")
    (compat
      ((reasoning_field reasoning_content)
       (max_tokens_field max_tokens)
       (require_tool_result_name false)
       (enable_thinking_field enable_thinking)))
    (models
      (((name kimi-k2-0905-preview)
        (context_window 262144)
        (max_tokens 32768)
        (thinking ((budget_medium 8000) (budget_high 32000)))
        (cost ((input_per_mtok "0.6") (output_per_mtok "2.5")
               (cache_read_per_mtok "0.15")))))))
   ((name github-copilot)
    (protocol openai-completions)
    (api "https://api.githubcopilot.com")
    (api_key_env (GITHUB_TOKEN GH_TOKEN))
    (models
      (((name claude-sonnet-4.5)
        (context_window 128000)
        (max_tokens 16384))
       ((name gpt-4o)
        (context_window 128000)
        (max_tokens 16384))
       ((name gemini-2.5-pro)
        (context_window 1000000)
        (max_tokens 65536)))))
   ((name github-models)
    (protocol openai-completions)
    (api "https://models.github.ai/inference")
    (api_key_env (GITHUB_TOKEN GH_TOKEN))
    (models
      (((name openai/gpt-4o)
        (context_window 128000)
        (max_tokens 16384))
       ((name meta/meta-llama-3.1-405b-instruct)
        (context_window 128000)
        (max_tokens 8192)))))
   ((name local)
    (protocol openai-completions)
    (api_key_env ())
    (api "http://localhost:11434")
    (api_env OLLAMA_BASE_URL)
    (models
      (((name qwen2.5-coder:14b)
        (context_window 32768)
        (max_tokens 8192))))))))
