(library
 (name pera_tools_test_util)
 (wrapped false)
 (modules test_util)
 (libraries containers eio cstruct pera_harness alcotest))

(tests
 (names read_tool_test write_tool_test bash_tool_test grep_tool_test)
 (modules read_tool_test write_tool_test bash_tool_test grep_tool_test)
 (libraries pera_tools_test_util pera_tools pera_harness pera_types eio eio_main eio_linux alcotest containers))
